In [1]:
#Importing Libraries
import pandas as pd
import numpy as np
import os

# Importing Datasets

In [2]:
#Importing Dataset

path= r'/Users/alejandroguillen/Documents/Instacart Basket Analysis'

In [3]:
ords_prods_merge = pd.read_pickle(os.path.join(path,'02 Data','Prepared Data','orders_products_merged_updated.pkl'))

# Creating subset of the first one million entries

In [4]:
df = ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 18)

In [6]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders

In [7]:
df.groupby('product_name')

# Aggregating data with agg

In [8]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [9]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [10]:
# Multiple aggregations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

# Aggregating data with transform

In [11]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [12]:
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10

In [13]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,22

In [14]:
pd.options.display.max_rows = None

In [15]:
#Checking output
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27
37,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,24
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,7
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,7
58,1889835,82,1,3,15,NaN,196,6,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,19
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,19
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,14
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,14
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,14
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,6
75,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6
78,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,58
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,58
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,70
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,70
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,51
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,51
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,8
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,22

# Creating flag column for loyalty customers

In [16]:
#Deriving columns with the loc funtion
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [17]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [18]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [19]:
ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [20]:
#Checking output
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

# 4.8

## Step 1: done

## Step 2

### In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [21]:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

# Step 3

### Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

In [22]:
#Previous subset
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

### Observation: with the entire dataframe there is a bigger span in averages (15.2 through 22.9) while with the subset is more limited (with exception of 11.29). The entire dataset allows us to see the shape of the averages more clearly.

# Step 4: Done (check output 11 through 20)

# Step 5:Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer).

In [23]:
# Group by "prices" 
ords_prods_merge.groupby('prices')

In [24]:
# Split the data into groups by "loyalty_flag" and then calculate the mean for each "prices" column
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean']})

                    prices
                      mean
loyalty_flag
Loyal customer    7.772831
New customer      7.800320
Regular customer  7.797431

### Observation: New Customers have the highest price mean.

# Step 6: Create a spending flag for each user based on the average price across all their orders

In [25]:
# Group data by "user_id" column, and create a mean/product aggregation and column
ords_prods_merge['mean_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [26]:
# Check output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,6.367797
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797

In [27]:
# Create flags 
ords_prods_merge.loc[ords_prods_merge['mean_price'] < 10, 'spending_flag'] = 'Low spender'

In [28]:
ords_prods_merge.loc[ords_prods_merge['mean_price'] >= 10, 'spending_flag'] = 'High spender'

In [29]:
ords_prods_merge['spending_flag'].value_counts (dropna=False)

Low spender     32285165
High spender      119694
Name: spending_flag, dtype: int64

In [30]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,6.367797,Low spender
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,6.367797,Low spender
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,6.367797,Low spender
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797,Low spender
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797,Low spender
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,6.367797,Low spender
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797,Low spender
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,22,Regular customer,3.980556,Low spender
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,22,Regular customer,3.980556,Low spender
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,9,New customer,8.372059,Low spender
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,9,New customer,8.372059,Low spender
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,9,New customer,8.372059,Low spender
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33,Regular customer,7.012683,Low spender
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,20,Regular customer,8.137793,Low spender
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20,Regular customer,8.137793,Low spender
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898,Low spender
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898,Low spender
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,27,Regular customer,6.356287,Low spender
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,27,Regular customer,6.356287,Low spender
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender
37,3205960,67,1,3,11,NaN,196,1,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
50,768572,67,16,4,10,9.0,196,1,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender
51,150528,67,18,5,16,4.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender
52,29758,67,19,0,14,9.0,196,2,1,Soda,...,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
53,1558976,67,21,1,9,5.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
54,863974,67,22,1,11,14.0,196,3,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
55,2308399,67,23,1,14,14.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
56,2759128,81,3,1,9,14.0,196,2,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,7,New customer,8.165385,Low spender
57,1812985,81,5,2,20,30.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,7,New customer,8.165385,Low spender
58,1889835,82,1,3,15,NaN,196,6,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,19,Regular customer,6.441221,Low spender
59,499460,82,3,5,10,5.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender
60,2728456,82,4,0,11,16.0,196,1,1,Soda,...,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19,Regular customer,6.441221,Low spender
61,2653743,82,6,4,9,13.0,196,5,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,19,Regular customer,6.441221,Low spender
62,1358880,82,9,1,10,30.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender
63,343588,82,10,2,11,1.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender
64,3034663,82,15,2,11,12.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender
65,147262,82,18,1,13,7.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender
66,3144004,82,19,2,15,8.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender
67,2126069,98,3,0,9,25.0,196,7,0,Soda,...,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer,8.028000,Low spender
68,2210120,98,7,5,14,5.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,14,Regular customer,8.028000,Low spender
69,681011,98,9,3,9,30.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,14,Regular customer,8.028000,Low spender
70,2846344,98,11,4,13,15.0,196,2,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14,Regular customer,8.028000,Low spender
71,747431,98,12,6,13,30.0,196,4,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,14,Regular customer,8.028000,Low spender
72,2383054,98,13,4,11,30.0,196,1,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14,Regular customer,8.028000,Low spender
73,1993729,98,14,5,8,8.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,14,Regular customer,8.028000,Low spender
74,1403849,109,3,3,17,9.0,196,5,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,6,New customer,5.850725,Low spender
75,520620,120,1,3,11,NaN,196,2,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,9.385714,Low spender
76,3273029,120,3,2,8,19.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,3,New customer,9.385714,Low spender
77,1861943,185,2,1,12,25.0,196,10,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6,New customer,7.715000,Low spender
78,2040988,195,1,1,14,NaN,196,2,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender
79,1680569,195,8,1,9,4.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender
80,276171,195,19,5,11,3.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender
81,2744976,195,22,5,10,7.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender
82,2781919,195,25,1,14,4.0,196,1,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender
83,1738718,195,31,2,8,4.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,58,Loyal customer,7.149730,Low spender
84,3058369,195,34,3,10,6.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender
85,1485596,195,37,2,15,0.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender
86,417035,195,40,3,16,2.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender
87,1615297,195,47,5,10,2.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender
88,1765587,195,52,3,12,2.0,196,3,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender
89,745908,195,57,4,11,3.0,196,3,1,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender
90,2505656,222,17,2,12,1.0,196,2,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,70,Loyal customer,6.862397,Low spender
91,3268370,222,38,5,15,1.0,196,6,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,70,Loyal customer,6.862397,Low spender
92,2016711,290,9,5,19,6.0,196,8,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Average orders,51,Loyal customer,7.285597,Low spender
93,2706088,290,28,6,10,7.0,196,16,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,51,Loyal customer,7.285597,Low spender
94,1952286,331,6,5,16,30.0,196,8,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,8,New customer,7.705128,Low spender
95,3226575,360,1,5,12,NaN,196,1,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,3,New customer,10.006250,High spender
96,1469869,377,3,5,17,3.0,196,9,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Regular days,Most orders,3,New customer,8.496552,Low spender
97,1927023,387,2,4,10,22.0,196,3,0,Soda,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8,New customer,7.396610,Low spender
98,858092,420,4,1,19,30.0,196,2,0,Soda,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22,Regular customer,7.387805,Low spender
99,119314,420,5,3,19,16.0,196,2,1,Soda,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,22,Regular customer,7.387805,Low spender

# Step 7: Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column.

In [31]:
# Group data by "user_id" column
ords_prods_merge['median_on_days'] = ords_prods_merge.groupby(['user_id'])['days_since_last_order'].transform(np.median)

In [32]:
# Check output
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_on_days
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Average orders,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Average orders,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,1,3,11,NaN,196,1,0,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
50,768572,67,16,4,10,9.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
51,150528,67,18,5,16,4.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,24,Regular customer,7.656790,Low spender,7.0
52,29758,67,19,0,14,9.0,196,2,1,Soda,...,both,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
53,1558976,67,21,1,9,5.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
54,863974,67,22,1,11,14.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
55,2308399,67,23,1,14,14.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
56,2759128,81,3,1,9,14.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,7,New customer,8.165385,Low spender,30.0
57,1812985,81,5,2,20,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,7,New customer,8.165385,Low spender,30.0
58,1889835,82,1,3,15,NaN,196,6,0,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
59,499460,82,3,5,10,5.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender,11.5
60,2728456,82,4,0,11,16.0,196,1,1,Soda,...,both,Mid-range product,Busiest day,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
61,2653743,82,6,4,9,13.0,196,5,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
62,1358880,82,9,1,10,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
63,343588,82,10,2,11,1.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender,11.5
64,3034663,82,15,2,11,12.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender,11.5
65,147262,82,18,1,13,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
66,3144004,82,19,2,15,8.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,19,Regular customer,6.441221,Low spender,11.5
67,2126069,98,3,0,9,25.0,196,7,0,Soda,...,both,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer,8.028000,Low spender,25.0
68,2210120,98,7,5,14,5.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,14,Regular customer,8.028000,Low spender,25.0
69,681011,98,9,3,9,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,14,Regular customer,8.028000,Low spender,25.0
70,2846344,98,11,4,13,15.0,196,2,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,14,Regular customer,8.028000,Low spender,25.0
71,747431,98,12,6,13,30.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,14,Regular customer,8.028000,Low spender,25.0
72,2383054,98,13,4,11,30.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,14,Regular customer,8.028000,Low spender,25.0
73,1993729,98,14,5,8,8.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,14,Regular customer,8.028000,Low spender,25.0
74,1403849,109,3,3,17,9.0,196,5,0,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,6,New customer,5.850725,Low spender,26.0
75,520620,120,1,3,11,NaN,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,9.385714,Low spender,19.0
76,3273029,120,3,2,8,19.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,3,New customer,9.385714,Low spender,19.0
77,1861943,185,2,1,12,25.0,196,10,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,6,New customer,7.715000,Low spender,25.0
78,2040988,195,1,1,14,NaN,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
79,1680569,195,8,1,9,4.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
80,276171,195,19,5,11,3.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
81,2744976,195,22,5,10,7.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
82,2781919,195,25,1,14,4.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
83,1738718,195,31,2,8,4.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,58,Loyal customer,7.149730,Low spender,4.0
84,3058369,195,34,3,10,6.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
85,1485596,195,37,2,15,0.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
86,417035,195,40,3,16,2.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
87,1615297,195,47,5,10,2.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
88,1765587,195,52,3,12,2.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
89,745908,195,57,4,11,3.0,196,3,1,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
90,2505656,222,17,2,12,1.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,70,Loyal customer,6.862397,Low spender,5.0
91,3268370,222,38,5,15,1.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,70,Loyal customer,6.862397,Low spender,5.0
92,2016711,290,9,5,19,6.0,196,8,0,Soda,...,both,Mid-range product,Regularly busy,Regular days,Average orders,51,Loyal customer,7.285597,Low spender,7.0
93,2706088,290,28,6,10,7.0,196,16,1,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,51,Loyal customer,7.285597,Low spender,7.0
94,1952286,331,6,5,16,30.0,196,8,0,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,8,New customer,7.705128,Low spender,30.0
95,3226575,360,1,5,12,NaN,196,1,0,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,3,New customer,10.006250,High spender,4.0
96,1469869,377,3,5,17,3.0,196,9,0,Soda,...,both,Mid-range product,Regularly busy,Regular days,Most orders,3,New customer,8.496552,Low spender,16.5
97,1927023,387,2,4,10,22.0,196,3,0,Soda,...,both,Mid-range product,Least busy,Slowest days,Most orders,8,New customer,7.396610,Low spender,8.0
98,858092,420,4,1,19,30.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Average orders,22,Regular customer,7.387805,Low spender,7.0
99,119314,420,5,3,19,16.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Slowest days,Average orders,22,Regular customer,7.387805,Low spender,7.0

In [33]:
# Create flags 
ords_prods_merge.loc[ords_prods_merge['median_on_days'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [34]:
ords_prods_merge.loc[(ords_prods_merge['median_on_days'] > 10) & (ords_prods_merge['median_on_days'] <= 20), 'frequency_flag'] = 'Regular customer'

In [35]:
ords_prods_merge.loc[ords_prods_merge['median_on_days'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [36]:
# Check output
ords_prods_merge['frequency_flag'].value_counts(dropna=False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: frequency_flag, dtype: int64

In [37]:
# Check null values
print(ords_prods_merge[ords_prods_merge.frequency_flag.isnull()])

          order_id  user_id  order_number  orders_day_of_week  \
13645692    895835   159838             1                   0
17251990    895835   159838             1                   0
17622767    895835   159838             1                   0
24138593    895835   159838             1                   0
25880002    895835   159838             1                   0

          order_hour_of_day  days_since_last_order  product_id  \
13645692                 17                    NaN       10749
17251990                 17                    NaN       33401
17622767                 17                    NaN       23695
24138593                 17                    NaN       21334
25880002                 17                    NaN       22198

          add_to_cart_order  reordered  \
13645692                  3          0
17251990                  6          0
17622767                  2          0
24138593                  5          0
25880002                  1          0

                                               product_name  ...  \
13645692                            Organic Red Bell Pepper  ...
17251990                               Goat Cheese Crumbles  ...
17622767                           California Veggie Burger  ...
24138593                              Organic Peeled Garlic  ...
25880002  4X Ultra Concentrated Natural Laundry Detergen...  ...

            price_range_loc  busiest_day  busiest_days busiest_period_of_day  \
13645692  Mid-range product  Busiest day  Busiest days           Most orders
17251990  Mid-range product  Busiest day  Busiest days           Most orders
17622767  Low-range product  Busiest day  Busiest days           Most orders
24138593  Mid-range product  Busiest day  Busiest days           Most orders
25880002  Low-range product  Busiest day  Busiest days           Most orders

         max_order  loyalty_flag mean_price spending_flag  median_on_days  \
13645692         1  New customer       7.42   Low spender             NaN
17251990         1  New customer       7.42   Low spender             NaN
17622767         1  New customer       7.42   Low spender             NaN
24138593         1  New customer       7.42   Low spender             NaN
25880002         1  New customer       7.42   Low spender             NaN

         frequency_flag
13645692            NaN
17251990            NaN
17622767            NaN
24138593            NaN
25880002            NaN

[5 rows x 24 columns]

### Observation: the null values are from customers who have only ordered once.

In [38]:
# Changing the null values to "Non-frequent customer"
ords_prods_merge['frequency_flag'].fillna("Non-frequent customer", inplace = True)

In [39]:
ords_prods_merge['frequency_flag'].value_counts(dropna=False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636442
Name: frequency_flag, dtype: int64

In [40]:
# Export 
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_aggregated.pkl'))